-- GreptimeDB schema for jorm's request/response recording.
--
-- GreptimeDB is a time-series database: every table needs exactly one
-- TIME INDEX (timestamp) column, and TIME INDEX cannot be changed once a
-- table is created. PRIMARY KEY declares "tag" columns used for storage
-- grouping/ordering -- unlike a relational primary key, it does not
-- enforce uniqueness. Our ids are always freshly generated per write, so
-- that's a non-issue in practice.
--
-- GreptimeDB has no SERIAL / IDENTITY / gen_random_uuid(), so "id" values
-- are generated by the application (SecureRandom.uuid) at insert time.
-- "jorm_request_id" is the proxy-level UUID that ties a request row to its
-- response_chunks rows.
--
-- Applied via `bin/migrate` (idempotent thanks to IF NOT EXISTS).
-- Schema changes that rename/add key columns require dropping the old
-- tables first -- IF NOT EXISTS will not alter an existing table.
--
-- Column names are all double-quoted because several plain words we'd
-- otherwise use ("id", "method", "status", ...) are reserved keywords
-- in GreptimeDB's SQL parser. Quote them the same way in every
-- INSERT/SELECT that references these tables.

CREATE TABLE IF NOT EXISTS requests (
  "id" STRING,                -- row UUID, generated by the app at insert time
  "jorm_request_id" STRING,   -- Jorm::Request#jorm_request_id -- ties to response_chunks
  "created_at" TIMESTAMP TIME INDEX DEFAULT CURRENT_TIMESTAMP(),
  "method" STRING,
  "path" STRING,              -- path_with_query_string, e.g. "/v1/messages?beta=true"
  "upstream_path" STRING,
  "patched" BOOLEAN,
  "headers" STRING,           -- redacted request headers, JSON-encoded
  "body" STRING,              -- redacted request body (post-patch)
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS response_chunks (
  "id" STRING,                -- per-chunk UUID, generated at write time
  "jorm_request_id" STRING,   -- ties to requests.jorm_request_id (no enforced FK)
  "chunk_index" INT32,         -- 0-based order within the stream
  "created_at" TIMESTAMP TIME INDEX DEFAULT CURRENT_TIMESTAMP(),
  "status" INT16,              -- only set on chunk_index = 0
  "headers" STRING,            -- redacted response headers, JSON-encoded; only set on chunk_index = 0
  "body" STRING,               -- this chunk's raw text (best-effort UTF-8)
  PRIMARY KEY ("jorm_request_id", "id")
);
