-- GreptimeDB schema for jorm's request/response recording.
--
-- GreptimeDB is a time-series database: every table needs exactly one
-- TIME INDEX (timestamp) column, and TIME INDEX cannot be changed once a
-- table is created. PRIMARY KEY declares "tag" columns used for storage
-- grouping/ordering -- unlike a relational primary key, it does not
-- enforce uniqueness. Our ids are always freshly generated per write, so
-- that's a non-issue in practice.
--
-- GreptimeDB has no SERIAL / IDENTITY / gen_random_uuid(), so "id" values
-- are generated by the application (SecureRandom.uuid) at insert time.
-- "jorm_request_id" is the proxy-level UUID that ties a request row to
-- its response row.
--
-- Applied via `bin/migrate` (idempotent thanks to IF NOT EXISTS).
-- Schema changes that rename/add key columns require dropping the old
-- tables first -- IF NOT EXISTS will not alter an existing table.
--
-- Column names are all double-quoted because several plain words we'd
-- otherwise use ("id", "method", "status", ...) are reserved keywords
-- in GreptimeDB's SQL parser. Quote them the same way in every
-- INSERT/SELECT that references these tables.
--
-- "headers" uses GreptimeDB's JSON type (there is no JSONB) so it can be
-- queried with json_get_string/json_get_int etc. "body"/"patched_body"
-- stay STRING -- request/response bodies aren't guaranteed to be valid
-- JSON (empty body, non-JSON content type, ...) and GreptimeDB's JSON
-- type rejects non-JSON text on insert.

CREATE TABLE IF NOT EXISTS requests (
  "id" STRING,                -- row UUID, generated by the app at insert time
  "jorm_request_id" STRING,   -- Jorm::Request#jorm_request_id -- ties to the responses row
  "created_at" TIMESTAMP TIME INDEX DEFAULT CURRENT_TIMESTAMP(),
  "method" STRING,
  "path" STRING,              -- path_with_query_string, e.g. "/v1/messages?beta=true"
  "upstream_path" STRING,
  "patched" BOOLEAN,
  "headers" JSON,              -- redacted request headers
  "body" STRING,               -- redacted original (pre-patch) request body
  "patched_body" STRING,       -- redacted body actually forwarded upstream
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS responses (
  "id" STRING,                -- row UUID, generated by the app at insert time
  "jorm_request_id" STRING,   -- ties to requests.jorm_request_id (no enforced FK)
  "created_at" TIMESTAMP TIME INDEX DEFAULT CURRENT_TIMESTAMP(),
  "status" INT16,
  "headers" JSON,              -- redacted response headers
  "body" STRING,               -- redacted response body (all chunks joined)
  PRIMARY KEY ("id")
);
